### ISSUE TITLE
Missing tournament reset request

### ISSUE THREAD

**Issue by ColinDTaylor** [alanhhwong/challonge-node#1]
I need something that can un-start a tournament for an application I'm building, I need to be able to start the tournament, grab the match data, and then reset the tournament. (so that I can project out the winners of the first few rounds)

This wrapper is perfect, except for the missing reset command :(

Hopefully you're still interested in working on this! If not I'll try to patch something together soon

**Comment by alanhhwong** [comment]
Added via this [PR](https://github.com/alanhhwong/challonge-node/pull/2)
