### ISSUE TITLE
Pulling package from NPM doesn't include reset method

### ISSUE THREAD

**Issue by austinhinderer** [alanhhwong/challonge-node#3]
I installed this package from NPM, and attempted to use the 'reset' method in the tournament api. It seems that without a patch version bump to 1.0.1, NPM is still serving your old version. Having never registered a package with NPM, I'm not sure if simply bumping the version in github is enough, or if you have to register it with NPM as well.

**Comment by alanhhwong** [comment]
Thanks for catching this @austinhinderer , I've just updated the npm package as well.
